# Generated by Django 4.1.7 on 2023-03-09 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='datetime',
        ),
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 13, 41, 39, 993315)),
        ),
    ]
