# Generated by Django 4.1.7 on 2023-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_journey_timestamp_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='metric',
        ),
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(default='New Goal', max_length=255),
        ),
    ]
