# Generated by Django 4.1.7 on 2023-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_goal_limit_goal_enddate_alter_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GoalProgress',
        ),
    ]
